<a href="https://colab.research.google.com/github/stalinjitala2001/prueba-2/blob/main/Te_damos_la_bienvenida_a_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

604800

In [3]:
def der_parcial_1(xs: list, ys: list) -> tuple[float, float, float]:
    """Retorna los coeficientes de la ecuación de la derivada parcial con respecto al parámetro 1 al reemplazar los valores ``xs`` y ``ys``. La ecuación es de la forma:
    c_1 * a_1 + c_0 * a_0 = c_ind

    ## Parameters

    ``xs``: lista de valores de x.

    ``ys``: lista de valores de y.

    ## Return

    ``c_1``: coeficiente del parámetro 1.

    ``c_0``: coeficiente del parámetro 0.

    ``c_ind``: coeficiente del término independiente.
    """
    sum_xi = sum(xs)
    sum_xi_squared = sum(x**2 for x in xs)
    sum_xi_yi = sum(x * y for x, y in zip(xs, ys))

    c_1 = -sum_xi_squared
    c_0 = -sum_xi
    c_ind = sum_xi_yi

    return (c_1, c_0, c_ind)





In [4]:
def der_parcial_0_parabol(xs: list, ys: list) -> tuple[float, float, float, float]:
    """Retorna los coeficientes de la ecuación de la derivada parcial con respecto al parámetro 0 al reemplazar los valores ``xs`` y ``ys``. La ecuación es de la forma:
    c_2 * a_2 + c_1 * a_1 + c_0 * a_0 = c_ind

    ## Parameters

    ``xs``: lista de valores de x.

    ``ys``: lista de valores de y.

    ## Return

    ``c_2``: coeficiente del parámetro 2.

    ``c_1``: coeficiente del parámetro 1.

    ``c_0``: coeficiente del parámetro 0.

    ``c_ind``: coeficiente del término independiente.
    """
    sum_xi = sum(xs)
    sum_yi = sum(ys)
    n = len(xs)

    c_2 = sum(1 for _ in xs)
    c_1 = sum_xi
    c_0 = n
    c_ind = sum_yi

    return (c_2, c_1, c_0, c_ind)







In [ ]:
def der_parcial_1_parabol(xs: list, ys: list) -> tuple[float, float, float, float]:
    """Retorna los coeficientes de la ecuación de la derivada parcial con respecto al parámetro 1 al reemplazar los valores ``xs`` y ``ys``. La ecuación es de la forma:
    c_2 * a_2 + c_1 * a_1 + c_0 * a_0 = c_ind

    ## Parameters

    ``xs``: lista de valores de x.

    ``ys``: lista de valores de y.

    ## Return

    ``c_2``: coeficiente del parámetro 2.

    ``c_1``: coeficiente del parámetro 1.

    ``c_0``: coeficiente del parámetro 0.

    ``c_ind``: coeficiente del término independiente.
    """
    sum_xi = sum(xs)
    sum_xi_squared = sum(x**2 for x in xs)
    sum_xi_yi = sum(x * y for x, y in zip(xs, ys))

    c_2 = sum_xi_squared
    c_1 = sum_xi
    c_0 = len(xs)
    c_ind = sum_xi_yi

    return (c_2, c_1, c_0, c_ind)

In [ ]:
def der_parcial_2_parabol(xs: list, ys: list) -> tuple[float, float, float, float]:
    """Retorna los coeficientes de la ecuación de la derivada parcial con respecto al parámetro 2 al reemplazar los valores ``xs`` y ``ys``. La ecuación es de la forma:
    c_2 * a_2 + c_1 * a_1 + c_0 * a_0 = c_ind

    ## Parameters

    ``xs``: lista de valores de x.

    ``ys``: lista de valores de y.

    ## Return

    ``c_2``: coeficiente del parámetro 2.

    ``c_1``: coeficiente del parámetro 1.

    ``c_0``: coeficiente del parámetro 0.

    ``c_ind``: coeficiente del término independiente.
    """
    sum_xi_squared = sum(x**2 for x in xs)
    sum_xi_cubed = sum(x**3 for x in xs)
    sum_xi_quadratic = sum(x**4 for x in xs)
    sum_xi_yi = sum(x * y for x, y in zip(xs, ys))

    c_2 = sum_xi_quadratic
    c_1 = sum_xi_cubed
    c_0 = sum_xi_squared
    c_ind = sum_xi_yi

    return (c_2, c_1, c_0, c_ind)


matrices

In [9]:
import numpy as np
import logging

# Configurar logging
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s: %(message)s')

def gauss_jordan_inversa(A: np.ndarray) -> np.ndarray:
    """Encuentra la inversa de una matriz cuadrada usando el método de Gauss-Jordan.

    ## Parameters

    ``A``: matriz cuadrada de tamaño n-by-n que se desea invertir.

    ## Return

    ``inversa``: matriz inversa de A.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A)

    n = A.shape[0]
    if A.shape[0] != A.shape[1]:
        raise ValueError("La matriz debe ser cuadrada.")

    # Crear matriz aumentada [A | I]
    Ab = np.hstack((A, np.eye(n)))
    logging.debug(f"Matriz aumentada inicial:\n{Ab}")

    for i in range(n):  # loop por columna

        # --- encontrar pivote
        p = np.argmax(np.abs(Ab[i:n, i])) + i
        if Ab[p, i] == 0:
            raise ValueError("La matriz no es invertible.")

        if p != i:
            # intercambiar filas
            logging.debug(f"Intercambiando filas {i} y {p}")
            Ab[[i, p], :] = Ab[[p, i], :]

        # --- Normalización
        Ab[i, :] = Ab[i, :] / Ab[i, i]
        logging.debug(f"Después de normalizar la fila {i}:\n{Ab}")

        # --- Eliminación: loop por fila
        for j in range(n):
            if i != j:
                m = Ab[j, i]
                Ab[j, :] = Ab[j, :] - m * Ab[i, :]
                logging.debug(f"Eliminando fila {j} usando la fila {i}:\n{Ab}")

    # Comprobar si la matriz es invertible
    if np.any(np.isnan(Ab[:, -n:])) or np.all(Ab[:, :-n] == 0):
        raise ValueError("La matriz no es invertible.")

    logging.debug(f"Matriz final aumentada:\n{Ab}")

    # --- Extracción de la inversa
    inversa = Ab[:, -n:]
    return inversa



In [13]:


# Ejercicio 3
A3 = np.array([
     [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10]
])


print("\nInversa de la matriz A3:")
print(gauss_jordan_inversa(A3))


Inversa de la matriz A3:
[[ 0.5 -0.5 -1.5  1.5]
 [-0.5  1.5 -1.5  0.5]
 [-1.5 -1.5  3.5 -1.5]
 [ 1.5  0.5 -1.5  0.5]]
